version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sprint"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fgtu1serlb0p"
s3_prefix = "sprint"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
